Switch to nightly_coverage to fix stable coverage runs
teoxoy/encase pull request #19
Opened 2022-11-27 20:27 UTC by emarcotte

For #18 

I also tried to make some of the tests pass when no feature flags are passed on `cargo test` with stable, but wasn't sure what to do about wrapper.rs which fails with:

```
test tests/pass/wrappers.rs [should pass] ... error
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> tests/pass/wrappers.rs:1:1
  |
1 | #![feature(trivial_bounds)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
``` 

Probably could address the mint usage in a more targeted fashion and completely killing the file. Happy to tweak this (or revert it entirely).

2022-12-03 23:17 UTC, teoxoy requested changes
Thanks for the PR!

I run the tests in CI using nightly due to the `trivial_bounds` feature needed for that test.
So, I think we can undo the `#![cfg(feature = "mint")]` additions for now and this should be good to go.

2022-12-04 17:28 UTC, emarcotte commented
> Thanks for the PR!
> 
> I run the tests in CI using nightly due to the `trivial_bounds` feature needed for that test. So, I think we can undo the `#![cfg(feature = "mint")]` additions for now and this should be good to go.

Reverted the mint check in tests/. Let me know if anything else I should check/change.

2022-12-09 22:11 UTC, teoxoy requested changes

2022-12-09 22:11 UTC, teoxoy commented on src/utils.rs
> +#[cfg_attr(coverage_nightly, feature(no_coverage))]
```suggestion
#[cfg_attr(coverage_nightly, no_coverage)]
```

2022-12-09 22:12 UTC, teoxoy approved these changes

2022-12-09 22:20 UTC, merged

2022-12-09 22:24 UTC, teoxoy commented
@emarcotte Thanks! I released v0.4.1