migrate to syn 2
teoxoy/encase pull request #35
Opened 2023-03-24 17:00 UTC by B-Reif

Updates `syn` version to `"2"` and updates usage.

2023-03-24 19:14 UTC, B-Reif commented
It looks like the failing tests are being compared to older `.stderr` files which contain errors related to deriving `ShaderType`:

Currently in `invalid_align_attr.stderr`:
```
error: expected attribute arguments in parentheses: #[align(...)]
 --> tests/compile_fail/invalid_align_attr.rs:5:10
  |
5 | #[derive(ShaderType)]
  |          ^^^^^^^^^^
  |
  = note: this error originates in the derive macro `ShaderType` (in Nightly builds, run with -Z macro-backtrace for more info)
```

This error isn't getting thrown in the new test result, which seems like the correct behavior? Let me know if anything needs to change here.

2023-03-27 21:23 UTC, teoxoy requested changes
Thank you for the PR!

We shouldn't have to update the expected error files; we seem to lose the span info now.

2023-03-27 21:23 UTC, teoxoy commented on derive/impl/src/lib.rs
> +                if attr.path().is_ident("align") {
I don't think this is correct and is why we seem to lose the span info.

We should use the new `attr.meta.require_list()` and work with `MetaList`s `.path` and `.tokens.span()`.

2023-03-27 23:03 UTC, B-Reif commented
Having some trouble compiling on my machine now, will resume fixing this later

2023-05-06 21:24 UTC, teoxoy approved these changes

2023-05-06 21:28 UTC, merged

2023-05-06 21:30 UTC, teoxoy commented
@B-Reif I ended up fixing the remaining issues since I wanted to release a new major version with the upgrade to syn2 included.